CENTER_FREQ: float = 40000.0
FREQ_SPACING: float = 200.0
NUMBER_OF_TEETH: int = 38
LASER_WAVELENGTH: float = 1645.56e-9
OPTICAL_COMB_SPACING: float = 1.0e9
ACQ_FREQ: float = 400000.0
SAMPLE_TAG: str = 'sample'
REFERENCE_TAG: str = 'reference'
TOOTH_STD_THRESHOLD: float = 0.1
DATABASE: str = 'hitran'
WAVELENGTH_STEP: float = 0.01
GPU_DEVICE_ID: str | int = 'nvidia'
ALLAN_NR_POINTS: int = 100
ALLAN_METHOD: str = 'adev'